### ISSUE TITLE
Custom comic nav image replacements display at wrong size.

### ISSUE THREAD

**Issue by Mihari** [mgsisk/inkblot#31]
Subject says it all, example here: http://roomiescomic.net/

**Comment by mgsisk** [comment]
Try adding this to the stylesheet in Customizer:

```css
.post-webcomic nav a { float: none; width: auto; }
```
I'm not sure I can fix this automatically via Inkblot's default CSS, but I'll check it out.

**Comment by Mihari** [comment]
Well, the float: none corrects the sizing, width: auto has no discernable effect, and thus the text doesn't center.

**Comment by mgsisk** [comment]
Try adding:
```css
.post-webcomic nav { text-align: center; }
```
