### ISSUE TITLE
Sidebar title "Primary Sidebar" sticks at top

### ISSUE THREAD

**Issue by radiochio** [mgsisk/inkblot#44]
I just updated to the latest Inkblot and my sidebar was stuck with "Primary Sidebar" displaying at the top, regardless of whether it contained any widgets. I was able to remove the extra title by editing line 17 of sidebar.php to change 'Primary Sidebar' to a space, like so:
```PHP
<h1 class="screen-reader-text"><?php _e(' ', 'inkblot'); ?></h1>
```
I realize this probably isn't the best solution...but I needed a quick fix. Not sure if this is just happening to me for some reason or if it's in general. Also not sure if it happens with other sidebars, as I really only use that one in my layout. I didn't see anything else about it, but figured I'd mention it anyway. Thanks!

**Comment by mgsisk** [comment]
Interesting. All of the sidebars gained titles in the v4.4.0 update for accessibility improvements, but the `screen-reader-text` class should've kept them hidden. This CSS should be in `style.css`:

```css
.screen-reader-text {
  border: 0;
  clip: rect(0 0 0 0);
  height: 1px;
  margin: -1px;
  overflow: hidden;
  padding: 0;
  position: absolute;
  width: 1px; }
```
Can you check to see if that exists? For what it's worth, anything with the `screen-reader-text` class can be safely removed from the theme; none of that text should be visible to normal users.
