### ISSUE TITLE
Insert AdSense banner into header and disable comic date and user name.

### ISSUE THREAD

**Issue by herrzeba1** [mgsisk/inkblot#65]
Hi, 

Great responsive theme!

www.danandclue.com is my website. I'd appreciate if you could help me with few issues. 

1. I'm trying to add Google Ad Banner to my header to align to the right. I edited header.php as well as functions.php after researching online, but I could only insert it either above or below the header. Actually, I managed to insert it where header is, but that caused the header to disappear.

2. I don't want Wordpress comments and I don't need date under comic nor any other stuff. I managed to add this to CSS: .post-footer {
display: none !important;
}
but it still shows date and "admin". I disabled all comments options in standard settings.

3. My comic is build from 3 separate images. Is there a way for them to remain current horizontal orientation before they kick in into responsive mode? (That is 3 panels on the same line, at specific width 3 of them become responsive and change to vertical). I played with responsive settings, but to no avail.

Please advise.
Thanks =)

**Comment by mgsisk** [comment]
Thanks @herrzeba1! For 1, you'll probably need to absolutely position the ad to get it where you want it; something like this may work:

```css

.ad-container { /* You'll want to change this selector to the actual class or ID of the element that has the ad code in it. */
  position: absolute;
  right: 1rem;
  top: 1rem;
}
```

For 2, you'll want to get rid of `.post-details`:

```css
.post-details {
  display: none; /* You shouldn't need !important */
}
```

For 3, you'll need some specific CSS to get this effect:

```css
.webcomic-image a {
  display: flex;
  flex-flow: column;
}

@media screen and (min-width: 1024px) { /* Or whatever width your full-size display should kick in at. */
  .webcomic-image a {
    align-items: center;
    flex-flow: row;
    justify-content: center;
  }

  .webcomic-image img {
    flex: 0 1 100%;
    width: 10%; /* The flex size above will take precedence. */
  }
}
```

**Comment by herrzeba1** [comment]
Hi @mgsisk 

Wow, this is amazing, thank you so much. For 2 & 3 it worked like a charm straight away!

I still can't get 1 working though.

Google code has this styling display:inline-block;width:728px;height:90px. I entered its script into HTML widget. The actual class or ID is .adsbygoogle. Then I added your code in Appearance -> Stylesheet.

`.adsbygoogle {
  position: absolute;
  right: 1rem;
  top: 1rem;
}`

It still removes my header or it places it behind the header, like it is now on my website. It's in Page Header widget, any other widget it's either above or below. I could alternatively remove my header centre align and make it shorter, so the ad will be visible. However the best would be just to place it inside the header. This is out of the box functionality with Comic Press, but as I mentioned, that solution is not responsive.

EDIT: Interestingly, when I click on next nav http://www.danandclue.com/dan-clue/test/, the ad is in front of the header, not below, hmm.. But in home it's under.

Thanks =)

**Comment by mgsisk** [comment]
No problem, glad to help! For the homepage, try adding `z-index: 1;` to the `.adbygoogle` block, like:

```css
.adsbygoogle {
  position: absolute;
  right: 1rem;
  top: 1rem;
  z-index: 1;
}
```
